const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const HeroSchema = new Schema({
    name: { type: String },
    quotes: { type: String },
    profile: { type: String },
    duelImage: { type: String },
    role: { type: [String] },
    price: {
        BP: { type: String },
        ticket: { type: Number },
        diamonds: { type: Number },
    },
    durability: { type: Number },
    offense: { type: Number },
    control_effect: { type: Number },
    difficulty: { type: Number },
    affiliation: { type: String },
    hp: { type: Number },
    mana: { type: Number },
    hp_regen: { type: Number },
    mana_regen: { type: Number },
    physical_attack: { type: Number },
    magic_power: { type: Number },
    physical_defense: { type: Number },
    magic_defense: { type: Number },
    physical_penetration: { type: Number },
    magic_penetration: { type: Number },
    damage_reduction: { type: Number },
    attack_speed: { type: Number },
    attack_speed_ratio: { type: Number },
    movement_speed: { type: Number },
    hp_Grow: { type: Number },
    mana_Grow: { type: Number },
    hp_regen_Grow: { type: Number },
    mana_regen_Grow: { type: Number },
    physical_attack_Grow: { type: Number },
    magic_power_Grow: { type: Number },
    physical_defense_Grow: { type: Number },
    magic_defense_Grow: { type: Number },
    physical_penetration_Grow: { type: Number },
    magic_penetration_Grow: { type: Number },
    damage_reduction_Grow: { type: Number },
    attack_speed_Grow: { type: Number },
    attack_speed_ratio_Grow: { type: Number },
    movement_speed_Grow: { type: Number },
    physical_lifesteal: { type: Number },
    magic_lifesteal: { type: Number },
    spell_vamp: { type: Number },
    critical_chance: { type: Number },
    healing_effect: { type: Number },
    bg: { type: String },
    specialty: { type: String },
    info: { type: String },
    skills: [
        {
            title: { type: String },
            skillNumber: { type: String },
            skillImage: { type: String },
            desc: {
                type: String,
            },
            title: { type: String },
            skillNumber: { type: String },
            skillImage: { type: String },
            desc: {
                type: String,
            },
            title: { type: String },
            skillNumber: { type: String },
            skillImage: { type: String },
            desc: {
                type: String,
            },
            title: { type: String },
            skillNumber: { type: String },
            skillImage: { type: String },
            desc: {
                type: String,
            },
        },
    ],
});

module.exports = mongoose.model("heroes", HeroSchema);
